/* Auto generated file by build envsetup shell.
 !!!!!!!! Do not edit this file. !!!!!!!!
 Created time : Wed Aug 13 11:26:27 KST 2014
TARGET_BUILD_BOARDVER : tp20
*/

#define CONFIG_BOARD_VER CONFIG_TP20

